### ISSUE TITLE
get sucked in extremely quickly to things in level select???

### ISSUE THREAD

**Issue by angusmason** [notangoose/The-Nine-Second-Rule#61]

**Comment by circles-png** [comment]
fading into level select changes alpha of the crossfade right
so when entering a level before the alpha changes from 1 to 0, for example 0.5
the alpha will then change in the opposite direction (0 -> 1 instead of 1 -> 0)
and if the vacuum speed is the same, the player will not get there before the alpha finishes getting back to 1

**Comment by circles-png** [comment]
so its fine if the player does not get to the end of the vacuum before the screen is completely black?
